<?xml version="1.0" encoding="UTF-8"?>
<robot name="prbot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find prbot_description)/urdf/robot.gazebo" />

  <xacro:property name="wheel_rad" value="0.05"/>
  <xacro:property name="wheel_len" value="0.025"/>
  <xacro:property name="body_x" value="0.3472"/>
  <xacro:property name="body_y" value="0.34852"/>
  <xacro:property name="body_z" value="0.40171"/>
  <xacro:property name="cam_len" value="0.03"/>
  <!-- square base for the prbot -->
  <link name="square_base">
    <!-- configure the phisics of the link -->
    <inertial>
      <mass value="5"/>
      <inertia  ixx="0.166667" ixy="0" ixz="0" iyy="0.166667" iyz="0" izz="0.166667"/>
    </inertial>
    <!-- configure the collition box for that link-->
    <collision name="base_collision">
      <geometry>
        <box size="${body_x} ${body_y} ${body_z}"/>
      </geometry>
    </collision>

    <!-- configure the visual for the link -->
    <visual name="base_visual">
      <geometry>
        <box size="${body_x} ${body_y} ${body_z}"/>
      </geometry>
    </visual>

    <!-- inside this link there is gonna be the caster_wheel-->
    <collision name="caster_collision">
      <origin xyz="${0.5*body_x-wheel_rad} 0 ${-body_z/2}" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${wheel_rad}"/>
      </geometry>
    </collision>

    <visual name="caster_visual">
      <origin xyz="${0.5*body_x-wheel_rad} 0 ${-body_z/2}" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${wheel_rad}"/>
      </geometry>
    </visual>

  </link>

  <!-- ################# right wheel #############################-->
  <link name="right_wheel">
    <pose xyz="${-0.5*body_x+wheel_rad} ${-body_y/2} ${-body_z/2}" rpy="-1.5707 0 0"/>
    <!-- configure the inertia of the wheel-->
    <inertial>
      <mass value="0.15"/>
      <inertia ixx="0.145833" ixy="0" ixz="0" iyy="0.145833" iyz="0" izz="0.125"/>
    </inertial>
    <!-- configure the collision box of the link -->
    <collision name="right_wheel_collision">
      <origin rpy= "-1.5707 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder radius="${wheel_rad}" length="${wheel_len}"/>
      </geometry>
    </collision>
    <!-- configure the visual for the link -->
    <visual name="right_wheel_visual">
      <origin rpy= "-1.5707 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder radius="${wheel_rad}" length="${wheel_len}"/>
      </geometry>
    </visual>
  </link>

  <!--##################### left wheel #########################-->
  <link name="left_wheel">
    <pose xyz="${-0.5*body_x+wheel_rad} ${body_y/2} ${-body_z/2}" rpy="-1.5707 0 0"/>
    <!-- configure the inertia of the wheel-->
    <inertial>
      <mass value="0.15"/>
      <inertia ixx="0.145833" ixy="0" ixz="0" iyy="0.145833" iyz="0" izz="0.125"/>
    </inertial>
    <!-- configure the collision box of the link -->
    <collision name="left_wheel_collision">
      <origin rpy= "-1.5707 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder radius="${wheel_rad}" length="${wheel_len}"/>
      </geometry>
    </collision>
    <!-- configure the visual for the link -->
    <visual name="left_wheel_visual">
      <origin rpy= "-1.5707 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder radius="${wheel_rad}" length="${wheel_len}"/>
      </geometry>
    </visual>
  </link>

  <!--##################### camera link #########################-->
  <link name="camera_box">
    <!-- configure the phisics of the link -->
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="1.5e-05" ixy="0" ixz="0" iyy="1.5e-05" iyz="0" izz="1.5e-05"/>
    </inertial>

    <!-- configure the collition box for the link-->
    <collision name="cam_collision">
      <geometry>
        <box size="${cam_len} ${3*cam_len} ${cam_len}"/>
      </geometry>
    </collision>

    <!-- configure the visual for the link -->
    <visual name="cam_visual">
      <geometry>
        <box size="${cam_len} ${3*cam_len} ${cam_len}"/>
      </geometry>
      </visual>
  </link>

  <!--##################### joints #########################-->
  <!-- joints for the two wheels -->
  <joint name="base2rightwheel" type="continuous">
    <origin xyz="${-body_x/2 + wheel_rad} ${-body_y/2} ${-body_z/2}" rpy= "0 0 0"/>
    <parent link="square_base"/>
    <child link="right_wheel"/>
    <axis xyz="0 1 0"/>
    <limit effort="10" velocity="6"/>
    <joint_properties damping="0.0" friction="0.001"/>
  </joint>

  <joint name="base2leftwheel" type="continuous">
    <origin xyz="${-body_x/2 + wheel_rad} ${body_y/2} ${-body_z/2}" rpy= "0 0 0"/>
    <parent link="square_base"/>
    <child link="left_wheel"/>
    <axis xyz="0 1 0"/>
    <limit effort="10" velocity="6"/>
    <joint_properties damping="0.0" friction="0.001"/>
  </joint>

    <!-- joint to attach the camera link to the body -->
  <joint name="base2camera_box" type="fixed">
    <origin rpy= "0 0 0" xyz="${body_x/2+cam_len/2} 0 0"/>
    <parent link="square_base"/>
    <child link="camera_box"/>
  </joint>

</robot>
